name: Build uOFW
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: krystalgamer/setup-psptoolchain@1.0
      - uses: actions/checkout@v2
      - name: Compile uOFW
        run: make
      - name: Install Doxygen
        run: sudo apt install doxygen
      - name: Build documentation
        run : |
          mkdir github-pages
          cd github-pages
          doxygen ../docs/Doxyfile
      - name: Deploy documentation
        if: github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: github-pages
          CLEAN: true
